# Generated by Django 3.2.7 on 2021-10-02 19:32

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('born_date', models.DateField()),
            ],
        ),
    ]
